#ifndef OTA_INTERNAL_H
#define OTA_INTERNAL_H

// TODO: ESP_ERROR_CHECK but esp_restart() instead of abort()

#define OTA_DEFAULT_SERVER "https://ota.leet.ar"

#define OTA_STATUS_AVAILABLE  200
#define OTA_STATUS_UP_TO_DATE 204
#define OTA_STATUS_NOT_FOUND  404

#define OTA_MAX_LENGTH_FIRMWARE_ID   26
#define OTA_MAX_LENGTH_FIRMWARE_HASH 64
#define OTA_MAX_LENGTH_SERVER_URL    128
#define OTA_MAX_URL_LENGTH           (OTA_MAX_LENGTH_FIRMWARE_ID + OTA_MAX_LENGTH_FIRMWARE_HASH + OTA_MAX_LENGTH_SERVER_URL)

#endif // OTA_INTERNAL_H
